In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#importing dataset
ds = pd.read_csv('https://raw.githubusercontent.com/Goutham0110/Mobile_price_classification_using_Naive_Bayes_classifier/main/train%20data%20mobile%20price%20classification.csv')
ds.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [5]:
#defining dependent and independent variables
x = ds.drop('price_range', axis=1)
y = ds['price_range']

#splitting data into training and testing set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [6]:
#Naive Bayes
#training model
nb = GaussianNB()
nb.fit(x_train,y_train)

#getting confusion matrix
y_pred = nb.predict(x_test)
print('confusion matrix:\n',confusion_matrix(y_test,y_pred))

#checking accuracy
print('\n\naccuracy score = \n',accuracy_score(y_test,y_pred))

confusion matrix:
 [[ 89   6   0   0]
 [  4  69  19   0]
 [  0  16  70  13]
 [  0   0   8 106]]


accuracy score = 
 0.835
